import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  shapeLightBlue: {
    position: 'absolute',
    top: -60,
    left: -40,
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: '#61B2F6',
  },
  shapePurple: {
    position: 'absolute',
    top: -40,
    right: -80,
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: '#8A7DF2',
  },
  scrollContent: {
    width: '100%',
    minHeight: '100%',
    alignItems: 'center',
  },
  content: {
    width: '100%',
    maxWidth: 340,
    marginTop: 145,
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  avatarContainer: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: '#61B2F6',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 18,
    overflow: 'hidden',
  },
  avatarIcon: {
    marginTop: 20,
  },
  title: {
    color: '#2F2F3A',
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 24,
    textAlign: 'center',
  },
  fields: {
    width: '100%',
    gap: 16,
  },
  input: {
    width: '100%',
    height: 48,
    backgroundColor: '#8A7DF2',
    borderRadius: 24,
    paddingHorizontal: 20,
    color: '#ffffff',
    fontSize: 15,
    textAlign: 'center',
  },
  rememberRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 16,
    marginBottom: 20,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  checkbox: {
    width: 18,
    height: 18,
    borderWidth: 1,
    borderColor: '#39A5F5',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#39A5F5',
    borderColor: '#39A5F5',
  },
  rememberText: {
    color: '#39A5F5',
    fontSize: 14,
  },
  message: {
    color: '#2F8F55',
    fontSize: 13,
    marginTop: 10,
    textAlign: 'center',
  },
  error: {
    color: '#FF3B30',
    fontSize: 13,
    marginTop: 10,
    textAlign: 'center',
  },
  submit: {
    width: 210,
    height: 48,
    backgroundColor: '#39A5F5',
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  submitText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 20,
    width: '100%',
  },
  dividerLine: {
    flex: 1,
    height: StyleSheet.hairlineWidth,
    backgroundColor: '#C6C0F5',
  },
  dividerText: {
    color: '#A0A0A0',
    fontSize: 13,
  },
  guestButton: {
    width: 210,
    height: 48,
    borderWidth: 1.5,
    borderColor: '#39A5F5',
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 16,
  },
  guestButtonText: {
    color: '#39A5F5',
    fontSize: 15,
    fontWeight: '600',
  },
  guestHint: {
    color: '#A0A0A0',
    fontSize: 12,
    marginTop: 10,
    textAlign: 'center',
  },
  modalWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.55)',
  },
  modalCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 22,
    alignItems: 'center',
  },
  modalIconContainer: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#EAF4FE',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  modalTitle: {
    color: '#2F2F3A',
    fontSize: 19,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 10,
  },
  modalMessage: {
    color: '#4B5563',
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
    marginBottom: 20,
  },
  modalButtons: {
    width: '100%',
    flexDirection: 'row',
    gap: 12,
  },
  modalButton: {
    flex: 1,
    height: 46,
    borderRadius: 23,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalButtonCancel: {
    backgroundColor: '#F1F1F6',
  },
  modalButtonCancelText: {
    color: '#2F2F3A',
    fontSize: 15,
    fontWeight: '600',
  },
  modalButtonConfirm: {
    backgroundColor: '#39A5F5',
  },
  modalButtonConfirmText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '600',
  },
  footerLinks: {
    marginTop: 24,
    alignItems: 'center',
  },
  footerButton: {
    minHeight: 28,
    justifyContent: 'center',
  },
  forgotText: {
    color: '#A0A0A0',
    fontSize: 13,
  },
  toggleModeText: {
    color: '#61B2F6',
    fontSize: 13,
    fontWeight: '500',
  },
  modeToggleButton: { marginTop: 24 },
});
