import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  shapeLightBlue: {
    position: 'absolute',
    top: -60,
    left: -40,
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: '#61B2F6',
  },
  shapePurple: {
    position: 'absolute',
    top: -40,
    right: -80,
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: '#8A7DF2',
  },
  content: {
    flex: 1,
    width: '100%',
    maxWidth: 320,
    marginTop: 220,
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  avatarContainer: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: '#61B2F6',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 40,
    overflow: 'hidden',
  },
  avatarIcon: {
    marginTop: 20,
  },
  fields: {
    width: '100%',
    gap: 16,
  },
  input: {
    width: '100%',
    height: 48,
    backgroundColor: '#8A7DF2',
    borderRadius: 24,
    paddingHorizontal: 20,
    color: '#ffffff',
    fontSize: 15,
    textAlign: 'center',
  },
  rememberRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 16,
    marginBottom: 20,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  checkbox: {
    width: 18,
    height: 18,
    borderWidth: 1,
    borderColor: '#39A5F5',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#39A5F5',
    borderColor: '#39A5F5',
  },
  rememberText: {
    color: '#39A5F5',
    fontSize: 14,
  },
  error: {
    color: '#FF3B30',
    fontSize: 13,
    marginTop: 10,
    textAlign: 'center',
  },
  submit: {
    width: 180,
    height: 48,
    backgroundColor: '#39A5F5',
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  submitText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  footerLinks: {
    marginTop: 24,
    alignItems: 'center',
  },
  forgotText: {
    color: '#A0A0A0',
    fontSize: 13,
  },
  toggleModeText: {
    color: '#61B2F6',
    fontSize: 13,
    fontWeight: '500',
  },
  modeToggleButton: { marginTop: 24 },
});
