import { StyleSheet } from 'react-native';
import { theme as appTheme } from '../constants/theme';

export const styles = StyleSheet.create({
  anchor: { position: 'relative', zIndex: 60 },
  compactGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  compactOption: { alignItems: 'center', borderRadius: 8, justifyContent: 'center', minHeight: 34, minWidth: 42, paddingHorizontal: 8, paddingVertical: 6 },
  container: { gap: 8, zIndex: 60 },
  label: { fontSize: 12, fontWeight: '700', textTransform: 'uppercase' },
  menu: { borderRadius: appTheme.radius.input, borderWidth: 1, left: 0, maxHeight: 360, overflow: 'hidden', position: 'absolute', right: 0, top: 54, zIndex: 120 },
  menuContent: { gap: 10, padding: 12 },
  menuScroll: { flexGrow: 0 },
  menuSectionLabel: { fontSize: 12, fontWeight: '700', textTransform: 'uppercase' },
  option: { alignItems: 'center', borderRadius: 8, flex: 1, justifyContent: 'center', minHeight: 36, minWidth: 64, paddingHorizontal: 10, paddingVertical: 8 },
  optionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  optionText: { fontFamily: appTheme.typography.body.fontFamily, fontSize: appTheme.typography.body.fontSize, lineHeight: appTheme.typography.body.lineHeight },
  periodRow: { flexDirection: 'row', gap: 8 },
  trigger: { alignItems: 'center', borderRadius: appTheme.radius.input, borderWidth: 1, flexDirection: 'row', gap: 8, justifyContent: 'space-between', minHeight: 48, paddingHorizontal: 14, paddingVertical: 12 },
  valueText: { flex: 1, fontSize: 16 },
  calendarHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  calendarMonthText: { fontFamily: appTheme.typography.title.fontFamily, fontSize: 18, fontWeight: 'bold' },
  iconButton: { padding: 8, borderRadius: 20 },
  calendarDaysHeader: { flexDirection: 'row', marginBottom: 8 },
  calendarDayHeaderText: { flex: 1, textAlign: 'center', fontSize: 12, fontWeight: 'bold', textTransform: 'uppercase' },
  calendarGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  calendarCellContainer: { width: '14.28%', aspectRatio: 1, padding: 2 },
  calendarCell: { flex: 1, justifyContent: 'center', alignItems: 'center', borderRadius: 999 },
  calendarCellText: { fontSize: 14 },
  clockContainer: { alignItems: 'center', justifyContent: 'center' },
  clockFace: { width: 180, height: 180, borderRadius: 90, position: 'relative', alignItems: 'center', justifyContent: 'center' },
  clockCenter: { width: 8, height: 8, borderRadius: 4, position: 'absolute', zIndex: 10 },
  handContainer: { position: 'absolute', width: 180, height: 180, alignItems: 'center', justifyContent: 'flex-start', zIndex: 5 },
  handLine: { width: 2, height: 72, marginTop: 18, borderRadius: 1 },
  handKnob: { width: 32, height: 32, borderRadius: 16, position: 'absolute', top: 2 },
  clockNumber: { position: 'absolute', width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center', zIndex: 20 },
  clockNumberText: { fontSize: 14, fontWeight: '600' },
  timeBox: { width: 64, height: 60, borderRadius: 8, backgroundColor: '#F1F5F9', alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: 'transparent' },
  timeBoxText: { fontSize: 32, fontWeight: '400' },
  periodToggleRow: { flexDirection: 'row', borderRadius: 8, borderWidth: 1, borderColor: '#CBD5E1', overflow: 'hidden' },
  periodToggleBtn: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 10 },
  periodToggleText: { fontSize: 14, fontWeight: '600' },
  calendarDayHeaderCell: { width: '14.28%', alignItems: 'center' },
  timeMenuContent: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 24, gap: 24 },
  timeInputColumn: { gap: 16 },
  timeInputRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  timeSeparatorText: { fontSize: 24, fontWeight: 'bold' },
  periodSeparator: { width: 1 },
  chevronLeft: { transform: [{ rotate: '-90deg' }] },
  chevronRight: { transform: [{ rotate: '90deg' }] },
});
